<?php

namespace Database\Seeders;

use App\Models\Exercise;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class ExerciseSeeder extends Seeder
{
    public function run(): void
    {
        $exercises = [
            // Peitoral (category_id: 1)
            [
                'name' => 'Supino Reto com Barra',
                'muscle_group' => 'Peitoral',
                'category_id' => 1,
                'equipment' => 'Barra',
                'difficulty' => 'Beginner',
                'description' => 'Exercício clássico para desenvolvimento do peitoral maior.',
                'instructions' => "1. Deite no banco reto com os pés apoiados no chão.\n2. Segure a barra com pegada pronada, um pouco mais larga que os ombros.\n3. Desça a barra até tocar levemente o peito.\n4. Empurre a barra de volta à posição inicial.",
                'image' => 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=400&h=300&fit=crop',
            ],
            [
                'name' => 'Supino Inclinado com Halteres',
                'muscle_group' => 'Peitoral',
                'category_id' => 1,
                'equipment' => 'Halteres',
                'difficulty' => 'Intermediate',
                'description' => 'Foco na porção superior do peitoral.',
                'instructions' => "1. Ajuste o banco a 30-45 graus de inclinação.\n2. Segure os halteres na altura do peito.\n3. Empurre os halteres para cima até estender os braços.\n4. Desça controladamente até a posição inicial.",
                'image' => 'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=400&h=300&fit=crop',
            ],
            [
                'name' => 'Crossover na Polia',
                'muscle_group' => 'Peitoral',
                'category_id' => 1,
                'equipment' => 'Cabo',
                'difficulty' => 'Intermediate',
                'description' => 'Excelente para isolamento e definição do peitoral.',
                'instructions' => "1. Fique no centro da máquina de cabos.\n2. Segure as alças com os braços abertos.\n3. Puxe as alças para frente, cruzando as mãos.\n4. Retorne lentamente à posição inicial.",
                'image' => 'https://images.unsplash.com/photo-1598971639058-fab3c3109e00?w=400&h=300&fit=crop',
            ],
            [
                'name' => 'Flexão de Braço',
                'muscle_group' => 'Peitoral',
                'category_id' => 1,
                'equipment' => 'Peso Corporal',
                'difficulty' => 'Beginner',
                'description' => 'Exercício funcional que pode ser feito em qualquer lugar.',
                'instructions' => "1. Apoie as mãos no chão na largura dos ombros.\n2. Mantenha o corpo reto da cabeça aos pés.\n3. Desça o peito até quase tocar o chão.\n4. Empurre o corpo de volta à posição inicial.",
                'image' => 'https://images.unsplash.com/photo-1598971639058-fab3c3109e00?w=400&h=300&fit=crop',
            ],
            [
                'name' => 'Crucifixo com Halteres',
                'muscle_group' => 'Peitoral',
                'category_id' => 1,
                'equipment' => 'Halteres',
                'difficulty' => 'Intermediate',
                'description' => 'Isolamento completo do peitoral maior.',
                'instructions' => "1. Deite no banco reto com halteres nas mãos.\n2. Abra os braços lateralmente com leve flexão nos cotovelos.\n3. Traga os halteres de volta ao centro acima do peito.\n4. Mantenha o movimento controlado.",
                'image' => 'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=400&h=300&fit=crop',
            ],

            // Costas (category_id: 2)
            [
                'name' => 'Barra Fixa',
                'muscle_group' => 'Costas',
                'category_id' => 2,
                'equipment' => 'Barra Fixa',
                'difficulty' => 'Advanced',
                'description' => 'Um dos melhores exercícios para costas e bíceps.',
                'instructions' => "1. Segure a barra com pegada pronada, mãos na largura dos ombros.\n2. Pendure-se com os braços estendidos.\n3. Puxe o corpo até o queixo ultrapassar a barra.\n4. Desça controladamente até a posição inicial.",
                'image' => 'https://images.unsplash.com/photo-1598971639058-fab3c3109e00?w=400&h=300&fit=crop',
            ],
            [
                'name' => 'Remada Curvada com Barra',
                'muscle_group' => 'Costas',
                'category_id' => 2,
                'equipment' => 'Barra',
                'difficulty' => 'Intermediate',
                'description' => 'Excelente para espessura das costas.',
                'instructions' => "1. Fique em pé com os joelhos levemente flexionados.\n2. Incline o tronco para frente mantendo as costas retas.\n3. Puxe a barra em direção ao abdômen.\n4. Desça controladamente.",
                'image' => 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=400&h=300&fit=crop',
            ],
            [
                'name' => 'Puxada Frontal',
                'muscle_group' => 'Costas',
                'category_id' => 2,
                'equipment' => 'Cabo',
                'difficulty' => 'Beginner',
                'description' => 'Alternativa à barra fixa para iniciantes.',
                'instructions' => "1. Sente na máquina e segure a barra com pegada larga.\n2. Puxe a barra até a altura do peito.\n3. Contraia as escápulas no final do movimento.\n4. Retorne lentamente à posição inicial.",
                'image' => 'https://images.unsplash.com/photo-1598971639058-fab3c3109e00?w=400&h=300&fit=crop',
            ],
            [
                'name' => 'Remada Unilateral com Halter',
                'muscle_group' => 'Costas',
                'category_id' => 2,
                'equipment' => 'Halteres',
                'difficulty' => 'Beginner',
                'description' => 'Trabalha cada lado das costas independentemente.',
                'instructions' => "1. Apoie um joelho e uma mão no banco.\n2. Segure o halter com a mão livre.\n3. Puxe o halter em direção ao quadril.\n4. Desça controladamente e repita.",
                'image' => 'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=400&h=300&fit=crop',
            ],
            [
                'name' => 'Remada Baixa',
                'muscle_group' => 'Costas',
                'category_id' => 2,
                'equipment' => 'Cabo',
                'difficulty' => 'Beginner',
                'description' => 'Foco na porção inferior e média das costas.',
                'instructions' => "1. Sente na máquina com os pés apoiados.\n2. Segure a alça com os braços estendidos.\n3. Puxe a alça em direção ao abdômen.\n4. Retorne lentamente à posição inicial.",
                'image' => 'https://images.unsplash.com/photo-1598971639058-fab3c3109e00?w=400&h=300&fit=crop',
            ],

            // Ombros (category_id: 3)
            [
                'name' => 'Desenvolvimento Militar',
                'muscle_group' => 'Ombros',
                'category_id' => 3,
                'equipment' => 'Barra',
                'difficulty' => 'Intermediate',
                'description' => 'Exercício composto para ombros e tríceps.',
                'instructions' => "1. Fique em pé com a barra na altura dos ombros.\n2. Empurre a barra para cima até estender os braços.\n3. Desça controladamente até a altura dos ombros.\n4. Mantenha o core ativado durante todo o movimento.",
                'image' => 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=400&h=300&fit=crop',
            ],
            [
                'name' => 'Elevação Lateral',
                'muscle_group' => 'Ombros',
                'category_id' => 3,
                'equipment' => 'Halteres',
                'difficulty' => 'Beginner',
                'description' => 'Isolamento da porção lateral do deltoide.',
                'instructions' => "1. Fique em pé com halteres ao lado do corpo.\n2. Eleve os braços lateralmente até a altura dos ombros.\n3. Mantenha os cotovelos levemente flexionados.\n4. Desça controladamente.",
                'image' => 'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=400&h=300&fit=crop',
            ],
            [
                'name' => 'Elevação Frontal',
                'muscle_group' => 'Ombros',
                'category_id' => 3,
                'equipment' => 'Halteres',
                'difficulty' => 'Beginner',
                'description' => 'Foco na porção anterior do deltoide.',
                'instructions' => "1. Fique em pé com halteres à frente das coxas.\n2. Eleve um braço de cada vez à frente até a altura dos ombros.\n3. Mantenha o braço reto com leve flexão no cotovelo.\n4. Alterne os braços de forma controlada.",
                'image' => 'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=400&h=300&fit=crop',
            ],
            [
                'name' => 'Face Pull',
                'muscle_group' => 'Ombros',
                'category_id' => 3,
                'equipment' => 'Cabo',
                'difficulty' => 'Intermediate',
                'description' => 'Excelente para saúde do ombro e deltoide posterior.',
                'instructions' => "1. Ajuste a polia na altura do rosto.\n2. Segure a corda com pegada neutra.\n3. Puxe a corda em direção ao rosto, abrindo os cotovelos.\n4. Contraia as escápulas no final do movimento.",
                'image' => 'https://images.unsplash.com/photo-1598971639058-fab3c3109e00?w=400&h=300&fit=crop',
            ],
            [
                'name' => 'Arnold Press',
                'muscle_group' => 'Ombros',
                'category_id' => 3,
                'equipment' => 'Halteres',
                'difficulty' => 'Intermediate',
                'description' => 'Variação do desenvolvimento que trabalha todas as porções do deltoide.',
                'instructions' => "1. Sente no banco com halteres na altura do peito, palmas viradas para você.\n2. Gire os halteres para frente enquanto empurra para cima.\n3. Estenda os braços completamente no topo.\n4. Desça girando de volta à posição inicial.",
                'image' => 'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=400&h=300&fit=crop',
            ],

            // Bíceps (category_id: 4)
            [
                'name' => 'Rosca Direta com Barra',
                'muscle_group' => 'Bíceps',
                'category_id' => 4,
                'equipment' => 'Barra',
                'difficulty' => 'Beginner',
                'description' => 'Exercício fundamental para desenvolvimento do bíceps.',
                'instructions' => "1. Fique em pé segurando a barra com pegada supinada.\n2. Flexione os cotovelos levantando a barra.\n3. Contraia o bíceps no topo do movimento.\n4. Desça controladamente sem balançar o corpo.",
                'image' => 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=400&h=300&fit=crop',
            ],
            [
                'name' => 'Rosca Alternada com Halteres',
                'muscle_group' => 'Bíceps',
                'category_id' => 4,
                'equipment' => 'Halteres',
                'difficulty' => 'Beginner',
                'description' => 'Permite maior amplitude e controle do movimento.',
                'instructions' => "1. Fique em pé com halteres ao lado do corpo.\n2. Flexione um braço de cada vez, girando a palma para cima.\n3. Contraia o bíceps no topo.\n4. Alterne os braços de forma controlada.",
                'image' => 'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=400&h=300&fit=crop',
            ],
            [
                'name' => 'Rosca Martelo',
                'muscle_group' => 'Bíceps',
                'category_id' => 4,
                'equipment' => 'Halteres',
                'difficulty' => 'Beginner',
                'description' => 'Trabalha o bíceps e o braquiorradial.',
                'instructions' => "1. Fique em pé com halteres e pegada neutra (palmas viradas uma para a outra).\n2. Flexione os cotovelos sem girar os pulsos.\n3. Contraia no topo do movimento.\n4. Desça controladamente.",
                'image' => 'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=400&h=300&fit=crop',
            ],
            [
                'name' => 'Rosca Scott',
                'muscle_group' => 'Bíceps',
                'category_id' => 4,
                'equipment' => 'Barra EZ',
                'difficulty' => 'Intermediate',
                'description' => 'Isolamento completo do bíceps sem auxílio de outros músculos.',
                'instructions' => "1. Sente no banco Scott com os braços apoiados.\n2. Segure a barra EZ com pegada supinada.\n3. Flexione os cotovelos levantando a barra.\n4. Desça controladamente até quase estender os braços.",
                'image' => 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=400&h=300&fit=crop',
            ],
            [
                'name' => 'Rosca Concentrada',
                'muscle_group' => 'Bíceps',
                'category_id' => 4,
                'equipment' => 'Halteres',
                'difficulty' => 'Intermediate',
                'description' => 'Máximo isolamento do pico do bíceps.',
                'instructions' => "1. Sente no banco com as pernas afastadas.\n2. Apoie o cotovelo na parte interna da coxa.\n3. Flexione o braço levantando o halter.\n4. Contraia fortemente no topo e desça lentamente.",
                'image' => 'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=400&h=300&fit=crop',
            ],

            // Tríceps (category_id: 5)
            [
                'name' => 'Tríceps Pulley',
                'muscle_group' => 'Tríceps',
                'category_id' => 5,
                'equipment' => 'Cabo',
                'difficulty' => 'Beginner',
                'description' => 'Exercício básico para desenvolvimento do tríceps.',
                'instructions' => "1. Fique em frente à polia alta com a barra reta ou corda.\n2. Mantenha os cotovelos fixos ao lado do corpo.\n3. Estenda os braços para baixo completamente.\n4. Retorne lentamente à posição inicial.",
                'image' => 'https://images.unsplash.com/photo-1598971639058-fab3c3109e00?w=400&h=300&fit=crop',
            ],
            [
                'name' => 'Tríceps Testa',
                'muscle_group' => 'Tríceps',
                'category_id' => 5,
                'equipment' => 'Barra EZ',
                'difficulty' => 'Intermediate',
                'description' => 'Foco na cabeça longa do tríceps.',
                'instructions' => "1. Deite no banco reto segurando a barra EZ acima do peito.\n2. Flexione os cotovelos descendo a barra em direção à testa.\n3. Estenda os braços de volta à posição inicial.\n4. Mantenha os cotovelos fixos durante o movimento.",
                'image' => 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=400&h=300&fit=crop',
            ],
            [
                'name' => 'Tríceps Francês',
                'muscle_group' => 'Tríceps',
                'category_id' => 5,
                'equipment' => 'Halteres',
                'difficulty' => 'Intermediate',
                'description' => 'Excelente para alongamento e contração do tríceps.',
                'instructions' => "1. Sente ou fique em pé segurando um halter com as duas mãos.\n2. Eleve o halter acima da cabeça.\n3. Flexione os cotovelos descendo o halter atrás da cabeça.\n4. Estenda os braços de volta à posição inicial.",
                'image' => 'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=400&h=300&fit=crop',
            ],
            [
                'name' => 'Mergulho em Paralelas',
                'muscle_group' => 'Tríceps',
                'category_id' => 5,
                'equipment' => 'Peso Corporal',
                'difficulty' => 'Advanced',
                'description' => 'Exercício composto para tríceps e peitoral.',
                'instructions' => "1. Apoie-se nas barras paralelas com os braços estendidos.\n2. Desça o corpo flexionando os cotovelos.\n3. Desça até os cotovelos formarem 90 graus.\n4. Empurre o corpo de volta à posição inicial.",
                'image' => 'https://images.unsplash.com/photo-1598971639058-fab3c3109e00?w=400&h=300&fit=crop',
            ],
            [
                'name' => 'Tríceps Kickback',
                'muscle_group' => 'Tríceps',
                'category_id' => 5,
                'equipment' => 'Halteres',
                'difficulty' => 'Beginner',
                'description' => 'Isolamento do tríceps com movimento controlado.',
                'instructions' => "1. Incline o tronco para frente com halteres nas mãos.\n2. Mantenha os cotovelos flexionados a 90 graus ao lado do corpo.\n3. Estenda os braços para trás completamente.\n4. Retorne lentamente à posição inicial.",
                'image' => 'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=400&h=300&fit=crop',
            ],

            // Abdômen (category_id: 7)
            [
                'name' => 'Abdominal Crunch',
                'muscle_group' => 'Abdômen',
                'category_id' => 7,
                'equipment' => 'Peso Corporal',
                'difficulty' => 'Beginner',
                'description' => 'Exercício clássico para abdominais.',
                'instructions' => "1. Deite de costas com os joelhos flexionados e pés no chão.\n2. Coloque as mãos atrás da cabeça ou cruzadas no peito.\n3. Eleve os ombros do chão contraindo o abdômen.\n4. Desça controladamente sem encostar completamente.",
                'image' => 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=400&h=300&fit=crop',
            ],
            [
                'name' => 'Prancha Frontal',
                'muscle_group' => 'Abdômen',
                'category_id' => 7,
                'equipment' => 'Peso Corporal',
                'difficulty' => 'Beginner',
                'description' => 'Excelente para fortalecimento do core.',
                'instructions' => "1. Apoie os antebraços e pontas dos pés no chão.\n2. Mantenha o corpo reto da cabeça aos calcanhares.\n3. Contraia o abdômen e glúteos.\n4. Mantenha a posição pelo tempo determinado.",
                'image' => 'https://images.unsplash.com/photo-1598971639058-fab3c3109e00?w=400&h=300&fit=crop',
            ],
            [
                'name' => 'Abdominal Infra',
                'muscle_group' => 'Abdômen',
                'category_id' => 7,
                'equipment' => 'Peso Corporal',
                'difficulty' => 'Intermediate',
                'description' => 'Foco na porção inferior do abdômen.',
                'instructions' => "1. Deite de costas com as mãos sob os glúteos.\n2. Eleve as pernas estendidas em direção ao teto.\n3. Eleve o quadril do chão contraindo o abdômen inferior.\n4. Desça controladamente sem encostar os pés no chão.",
                'image' => 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=400&h=300&fit=crop',
            ],
            [
                'name' => 'Russian Twist',
                'muscle_group' => 'Abdômen',
                'category_id' => 7,
                'equipment' => 'Peso Corporal',
                'difficulty' => 'Intermediate',
                'description' => 'Trabalha os oblíquos e o core.',
                'instructions' => "1. Sente no chão com os joelhos flexionados e pés elevados.\n2. Incline o tronco para trás formando um V.\n3. Gire o tronco de um lado para o outro.\n4. Mantenha o core ativado durante todo o movimento.",
                'image' => 'https://images.unsplash.com/photo-1598971639058-fab3c3109e00?w=400&h=300&fit=crop',
            ],
            [
                'name' => 'Mountain Climber',
                'muscle_group' => 'Abdômen',
                'category_id' => 7,
                'equipment' => 'Peso Corporal',
                'difficulty' => 'Intermediate',
                'description' => 'Exercício dinâmico para core e condicionamento.',
                'instructions' => "1. Comece na posição de prancha alta.\n2. Traga um joelho em direção ao peito.\n3. Alterne as pernas rapidamente como se estivesse correndo.\n4. Mantenha o quadril baixo e o core ativado.",
                'image' => 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=400&h=300&fit=crop',
            ],

            // Quadríceps (category_id: 8)
            [
                'name' => 'Agachamento Livre',
                'muscle_group' => 'Quadríceps',
                'category_id' => 8,
                'equipment' => 'Barra',
                'difficulty' => 'Intermediate',
                'description' => 'O rei dos exercícios para pernas.',
                'instructions' => "1. Posicione a barra nas costas, apoiada no trapézio.\n2. Fique com os pés na largura dos ombros.\n3. Desça flexionando os joelhos e quadril.\n4. Desça até as coxas ficarem paralelas ao chão e suba.",
                'image' => 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=400&h=300&fit=crop',
            ],
            [
                'name' => 'Leg Press 45°',
                'muscle_group' => 'Quadríceps',
                'category_id' => 8,
                'equipment' => 'Máquina',
                'difficulty' => 'Beginner',
                'description' => 'Excelente para quadríceps com menor impacto na lombar.',
                'instructions' => "1. Sente na máquina com as costas apoiadas.\n2. Posicione os pés na plataforma na largura dos ombros.\n3. Desça a plataforma flexionando os joelhos a 90 graus.\n4. Empurre a plataforma de volta sem travar os joelhos.",
                'image' => 'https://images.unsplash.com/photo-1598971639058-fab3c3109e00?w=400&h=300&fit=crop',
            ],
            [
                'name' => 'Cadeira Extensora',
                'muscle_group' => 'Quadríceps',
                'category_id' => 8,
                'equipment' => 'Máquina',
                'difficulty' => 'Beginner',
                'description' => 'Isolamento completo do quadríceps.',
                'instructions' => "1. Sente na máquina com as costas apoiadas.\n2. Posicione as canelas contra o rolo almofadado.\n3. Estenda as pernas completamente.\n4. Contraia o quadríceps no topo e desça controladamente.",
                'image' => 'https://images.unsplash.com/photo-1598971639058-fab3c3109e00?w=400&h=300&fit=crop',
            ],
            [
                'name' => 'Avanço com Halteres',
                'muscle_group' => 'Quadríceps',
                'category_id' => 8,
                'equipment' => 'Halteres',
                'difficulty' => 'Intermediate',
                'description' => 'Trabalha quadríceps, glúteos e equilíbrio.',
                'instructions' => "1. Fique em pé com halteres ao lado do corpo.\n2. Dê um passo à frente e desça o joelho de trás em direção ao chão.\n3. O joelho da frente deve ficar a 90 graus.\n4. Empurre de volta à posição inicial e alterne as pernas.",
                'image' => 'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=400&h=300&fit=crop',
            ],
            [
                'name' => 'Agachamento Búlgaro',
                'muscle_group' => 'Quadríceps',
                'category_id' => 8,
                'equipment' => 'Halteres',
                'difficulty' => 'Advanced',
                'description' => 'Exercício unilateral avançado para pernas.',
                'instructions' => "1. Apoie o peito do pé de trás em um banco.\n2. Segure halteres ao lado do corpo.\n3. Desça flexionando o joelho da frente até a coxa ficar paralela.\n4. Empurre de volta à posição inicial e repita.",
                'image' => 'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=400&h=300&fit=crop',
            ],

            // Posterior de Coxa (category_id: 9)
            [
                'name' => 'Stiff',
                'muscle_group' => 'Posterior de Coxa',
                'category_id' => 9,
                'equipment' => 'Barra',
                'difficulty' => 'Intermediate',
                'description' => 'Excelente para posteriores e glúteos.',
                'instructions' => "1. Fique em pé segurando a barra com os braços estendidos.\n2. Incline o tronco para frente mantendo as costas retas.\n3. Desça a barra rente às pernas até sentir o alongamento.\n4. Suba contraindo os glúteos e posteriores.",
                'image' => 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=400&h=300&fit=crop',
            ],
            [
                'name' => 'Mesa Flexora',
                'muscle_group' => 'Posterior de Coxa',
                'category_id' => 9,
                'equipment' => 'Máquina',
                'difficulty' => 'Beginner',
                'description' => 'Isolamento dos isquiotibiais.',
                'instructions' => "1. Deite de bruços na máquina com as canelas contra o rolo.\n2. Flexione os joelhos trazendo os calcanhares em direção aos glúteos.\n3. Contraia os posteriores no topo.\n4. Desça controladamente.",
                'image' => 'https://images.unsplash.com/photo-1598971639058-fab3c3109e00?w=400&h=300&fit=crop',
            ],
            [
                'name' => 'Cadeira Flexora',
                'muscle_group' => 'Posterior de Coxa',
                'category_id' => 9,
                'equipment' => 'Máquina',
                'difficulty' => 'Beginner',
                'description' => 'Variação sentada da flexora.',
                'instructions' => "1. Sente na máquina com as canelas contra o rolo inferior.\n2. Flexione os joelhos puxando o rolo para baixo.\n3. Contraia os posteriores no final do movimento.\n4. Retorne lentamente à posição inicial.",
                'image' => 'https://images.unsplash.com/photo-1598971639058-fab3c3109e00?w=400&h=300&fit=crop',
            ],
            [
                'name' => 'Levantamento Terra Romeno',
                'muscle_group' => 'Posterior de Coxa',
                'category_id' => 9,
                'equipment' => 'Halteres',
                'difficulty' => 'Intermediate',
                'description' => 'Foco nos isquiotibiais e glúteos.',
                'instructions' => "1. Fique em pé com halteres à frente das coxas.\n2. Incline o tronco para frente com leve flexão nos joelhos.\n3. Desça os halteres rente às pernas.\n4. Suba contraindo glúteos e posteriores.",
                'image' => 'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=400&h=300&fit=crop',
            ],
            [
                'name' => 'Good Morning',
                'muscle_group' => 'Posterior de Coxa',
                'category_id' => 9,
                'equipment' => 'Barra',
                'difficulty' => 'Advanced',
                'description' => 'Exercício avançado para cadeia posterior.',
                'instructions' => "1. Posicione a barra nas costas como no agachamento.\n2. Incline o tronco para frente com joelhos levemente flexionados.\n3. Desça até o tronco ficar paralelo ao chão.\n4. Suba contraindo a cadeia posterior.",
                'image' => 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=400&h=300&fit=crop',
            ],

            // Glúteos (category_id: 10)
            [
                'name' => 'Hip Thrust',
                'muscle_group' => 'Glúteos',
                'category_id' => 10,
                'equipment' => 'Barra',
                'difficulty' => 'Intermediate',
                'description' => 'O melhor exercício para ativação dos glúteos.',
                'instructions' => "1. Sente no chão com as costas apoiadas em um banco.\n2. Posicione a barra sobre o quadril.\n3. Eleve o quadril contraindo os glúteos no topo.\n4. Desça controladamente sem encostar no chão.",
                'image' => 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=400&h=300&fit=crop',
            ],
            [
                'name' => 'Elevação Pélvica',
                'muscle_group' => 'Glúteos',
                'category_id' => 10,
                'equipment' => 'Peso Corporal',
                'difficulty' => 'Beginner',
                'description' => 'Versão simplificada do hip thrust.',
                'instructions' => "1. Deite de costas com os joelhos flexionados e pés no chão.\n2. Eleve o quadril contraindo os glúteos.\n3. Mantenha a contração no topo por 1-2 segundos.\n4. Desça controladamente.",
                'image' => 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=400&h=300&fit=crop',
            ],
            [
                'name' => 'Abdução de Quadril na Máquina',
                'muscle_group' => 'Glúteos',
                'category_id' => 10,
                'equipment' => 'Máquina',
                'difficulty' => 'Beginner',
                'description' => 'Isolamento do glúteo médio.',
                'instructions' => "1. Sente na máquina com as pernas nas almofadas laterais.\n2. Empurre as pernas para fora contraindo os glúteos.\n3. Mantenha a contração no final do movimento.\n4. Retorne lentamente à posição inicial.",
                'image' => 'https://images.unsplash.com/photo-1598971639058-fab3c3109e00?w=400&h=300&fit=crop',
            ],
            [
                'name' => 'Agachamento Sumô',
                'muscle_group' => 'Glúteos',
                'category_id' => 10,
                'equipment' => 'Halteres',
                'difficulty' => 'Beginner',
                'description' => 'Foco nos glúteos e adutores.',
                'instructions' => "1. Fique com os pés mais largos que os ombros, pontas para fora.\n2. Segure um halter com as duas mãos à frente do corpo.\n3. Desça flexionando os joelhos e quadril.\n4. Suba contraindo os glúteos.",
                'image' => 'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=400&h=300&fit=crop',
            ],
            [
                'name' => 'Coice (Glúteo na Polia)',
                'muscle_group' => 'Glúteos',
                'category_id' => 10,
                'equipment' => 'Cabo',
                'difficulty' => 'Intermediate',
                'description' => 'Isolamento do glúteo máximo.',
                'instructions' => "1. Fique de frente para a máquina com a tornozeleira conectada ao cabo.\n2. Estenda a perna para trás contraindo o glúteo.\n3. Mantenha o tronco estável.\n4. Retorne lentamente à posição inicial.",
                'image' => 'https://images.unsplash.com/photo-1598971639058-fab3c3109e00?w=400&h=300&fit=crop',
            ],

            // Panturrilhas (category_id: 11)
            [
                'name' => 'Panturrilha em Pé na Máquina',
                'muscle_group' => 'Panturrilhas',
                'category_id' => 11,
                'equipment' => 'Máquina',
                'difficulty' => 'Beginner',
                'description' => 'Exercício básico para gastrocnêmio.',
                'instructions' => "1. Posicione os ombros sob as almofadas da máquina.\n2. Fique na ponta dos pés com os calcanhares para fora da plataforma.\n3. Eleve-se na ponta dos pés o máximo possível.\n4. Desça lentamente sentindo o alongamento.",
                'image' => 'https://images.unsplash.com/photo-1598971639058-fab3c3109e00?w=400&h=300&fit=crop',
            ],
            [
                'name' => 'Panturrilha Sentado',
                'muscle_group' => 'Panturrilhas',
                'category_id' => 11,
                'equipment' => 'Máquina',
                'difficulty' => 'Beginner',
                'description' => 'Foco no sóleo.',
                'instructions' => "1. Sente na máquina com as almofadas sobre as coxas.\n2. Posicione as pontas dos pés na plataforma.\n3. Eleve os calcanhares contraindo as panturrilhas.\n4. Desça lentamente até sentir o alongamento.",
                'image' => 'https://images.unsplash.com/photo-1598971639058-fab3c3109e00?w=400&h=300&fit=crop',
            ],
            [
                'name' => 'Panturrilha no Leg Press',
                'muscle_group' => 'Panturrilhas',
                'category_id' => 11,
                'equipment' => 'Máquina',
                'difficulty' => 'Intermediate',
                'description' => 'Variação usando o leg press.',
                'instructions' => "1. Sente no leg press com os pés na parte inferior da plataforma.\n2. Empurre a plataforma apenas com as pontas dos pés.\n3. Estenda os tornozelos completamente.\n4. Retorne lentamente à posição inicial.",
                'image' => 'https://images.unsplash.com/photo-1598971639058-fab3c3109e00?w=400&h=300&fit=crop',
            ],
            [
                'name' => 'Panturrilha Unilateral',
                'muscle_group' => 'Panturrilhas',
                'category_id' => 11,
                'equipment' => 'Peso Corporal',
                'difficulty' => 'Intermediate',
                'description' => 'Trabalha cada perna individualmente.',
                'instructions' => "1. Fique em pé em um degrau com uma perna.\n2. Eleve-se na ponta do pé o máximo possível.\n3. Mantenha a contração no topo por 1 segundo.\n4. Desça lentamente abaixo do nível do degrau.",
                'image' => 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=400&h=300&fit=crop',
            ],
            [
                'name' => 'Panturrilha no Smith',
                'muscle_group' => 'Panturrilhas',
                'category_id' => 11,
                'equipment' => 'Barra',
                'difficulty' => 'Intermediate',
                'description' => 'Permite maior carga com segurança.',
                'instructions' => "1. Posicione a barra do Smith sobre os ombros.\n2. Fique na ponta dos pés em uma plataforma elevada.\n3. Eleve-se na ponta dos pés contraindo as panturrilhas.\n4. Desça controladamente sentindo o alongamento.",
                'image' => 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=400&h=300&fit=crop',
            ],

            // Corpo Inteiro (category_id: 12)
            [
                'name' => 'Burpee',
                'muscle_group' => 'Corpo Inteiro',
                'category_id' => 12,
                'equipment' => 'Peso Corporal',
                'difficulty' => 'Advanced',
                'description' => 'Exercício completo para condicionamento físico.',
                'instructions' => "1. Fique em pé e agache colocando as mãos no chão.\n2. Salte os pés para trás ficando na posição de prancha.\n3. Faça uma flexão de braço.\n4. Salte os pés para frente e pule com os braços para cima.",
                'image' => 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=400&h=300&fit=crop',
            ],
            [
                'name' => 'Thruster',
                'muscle_group' => 'Corpo Inteiro',
                'category_id' => 12,
                'equipment' => 'Halteres',
                'difficulty' => 'Advanced',
                'description' => 'Combina agachamento com desenvolvimento.',
                'instructions' => "1. Segure halteres na altura dos ombros.\n2. Faça um agachamento completo.\n3. Ao subir, empurre os halteres para cima.\n4. Desça os halteres enquanto agacha novamente.",
                'image' => 'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=400&h=300&fit=crop',
            ],
            [
                'name' => 'Clean and Press',
                'muscle_group' => 'Corpo Inteiro',
                'category_id' => 12,
                'equipment' => 'Barra',
                'difficulty' => 'Advanced',
                'description' => 'Exercício olímpico para força total.',
                'instructions' => "1. Comece com a barra no chão.\n2. Puxe a barra explosivamente até os ombros.\n3. Empurre a barra para cima.\n4. Desça a barra e repita.",
                'image' => 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=400&h=300&fit=crop',
            ],
            [
                'name' => 'Kettlebell Swing',
                'muscle_group' => 'Corpo Inteiro',
                'category_id' => 12,
                'equipment' => 'Kettlebell',
                'difficulty' => 'Intermediate',
                'description' => 'Excelente para potência e condicionamento.',
                'instructions' => "1. Fique com os pés na largura dos ombros segurando o kettlebell.\n2. Balance o kettlebell para trás entre as pernas.\n3. Empurre o quadril para frente balançando o kettlebell à frente.\n4. Controle o retorno e repita.",
                'image' => 'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=400&h=300&fit=crop',
            ],
            [
                'name' => 'Remada Alta com Salto',
                'muscle_group' => 'Corpo Inteiro',
                'category_id' => 12,
                'equipment' => 'Barra',
                'difficulty' => 'Advanced',
                'description' => 'Combina força e explosão.',
                'instructions' => "1. Comece com a barra no chão.\n2. Puxe a barra explosivamente até o peito.\n3. Ao mesmo tempo, faça um salto.\n4. Aterrisse suavemente e repita.",
                'image' => 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=400&h=300&fit=crop',
            ],
        ];

        foreach ($exercises as $exercise) {
            Exercise::updateOrCreate(
                ['slug' => Str::slug($exercise['name'])],
                array_merge($exercise, ['is_active' => true]),
            );
        }
    }
}
